/* Experimental browser adaptations of hermesless.png. Not calibrated physics.
 * Original NumPy RNG is NOT reproduced. See ENGINE_ADAPTATIONS.md. */
(function(root){'use strict';
const radii={H:.37,C:.77,N:.75,O:.73,P:1.10,S:1.02,F:.71,Cl:.99,Br:1.14,Ti:1.33,Si:1.11,Se:1.16};
const norm=v=>Math.hypot(...v),sub=(a,b)=>a.map((v,i)=>v-b[i]),zeros=n=>Array.from({length:n},()=>Array(n).fill(0));
const radius=s=>{if(!(s in radii))throw Error('Element radius not defined');return radii[s];};
function check(elements,A,perturbations){const n=elements.length;if(n>24)throw Error('Experimental engines limited to 24 atoms');elements.forEach(radius);if(A.length!==n||A.some((r,i)=>r.length!==n||r.some((v,j)=>![0,1].includes(v)||v!==A[j]?.[i]||(i===j&&v!==0))))throw Error('Use symmetric binary adjacency with zero diagonal');if(perturbations&&(perturbations.length!==n||perturbations.some(v=>v.length!==3||!v.every(Number.isFinite))))throw Error('Use one finite 3D perturbation per atom');}
function distances(coords){return coords.map(a=>coords.map(b=>norm(sub(a,b))));}
function rng(seed){let x=seed>>>0;return ()=>{x=(1664525*x+1013904223)>>>0;return (x+.5)/4294967296;};}
function normalRandom(r){return Math.sqrt(-2*Math.log(r()))*Math.cos(2*Math.PI*r());}
function eigensystem(matrix){const n=matrix.length,A=matrix.map(r=>r.slice()),V=zeros(n);for(let i=0;i<n;i++)V[i][i]=1;let converged=false;
 for(let sweep=0;sweep<80;sweep++){let off=0,scale=1;for(let i=0;i<n;i++){scale=Math.max(scale,Math.abs(A[i][i]));for(let j=i+1;j<n;j++)off=Math.max(off,Math.abs(A[i][j]));}if(off<1e-12*scale){converged=true;break;}
  for(let p=0;p<n;p++)for(let q=p+1;q<n;q++){if(Math.abs(A[p][q])<1e-14*scale)continue;const angle=.5*Math.atan2(2*A[p][q],A[q][q]-A[p][p]),c=Math.cos(angle),s=Math.sin(angle),ap=A[p][p],aq=A[q][q],a=A[p][q];A[p][p]=c*c*ap-2*c*s*a+s*s*aq;A[q][q]=s*s*ap+2*c*s*a+c*c*aq;A[p][q]=A[q][p]=0;for(let k=0;k<n;k++){if(k!==p&&k!==q){const x=A[k][p],y=A[k][q];A[k][p]=A[p][k]=c*x-s*y;A[k][q]=A[q][k]=s*x+c*y;}const x=V[k][p],y=V[k][q];V[k][p]=c*x-s*y;V[k][q]=s*x+c*y;}}
 }if(!converged)throw Error('Eigen solver did not converge');const order=Array.from({length:n},(_,i)=>i).sort((i,j)=>A[i][i]-A[j][j]);return {values:order.map(i=>A[i][i]),vectors:order.map(i=>V.map(row=>row[i]))};}
function disposition(score,carry=.9,condition=.6){return score>carry?'CARRY':score>condition?'CONDITION':'REJECT';}
class CLCEEngine{
 compute_graph_properties(A){const n=A.length;if(n<=1)return {density:0,branches:0,triangles:0};check(Array(n).fill('C'),A);let edges=0,branches=0,triangles=0;for(let i=0;i<n;i++){const degree=A[i].reduce((a,b)=>a+b,0);edges+=degree;branches+=degree>=3?1:0;for(let j=i+1;j<n;j++)if(A[i][j])for(let k=j+1;k<n;k++)if(A[i][k]&&A[j][k])triangles++;}return {density:edges/(n*(n-1)),branches,triangles};}
 run_flow(atom_count,connectivity_density,noise_tau,feedback_alpha){if(!Number.isInteger(atom_count)||atom_count<0||atom_count>24||![connectivity_density,noise_tau,feedback_alpha].every(Number.isFinite)||connectivity_density<0||connectivity_density>1||noise_tau<0||noise_tau>1)throw Error('Invalid synthetic graph controls');const r=rng(42),A=zeros(atom_count);for(let i=0;i<atom_count;i++)for(let j=i+1;j<atom_count;j++)A[i][j]=A[j][i]=r()<connectivity_density?1:0;
 // Adaptation: flip unordered edges symmetrically; screenshot draws a full asymmetric mask.
 for(let i=0;i<atom_count;i++)for(let j=i+1;j<atom_count;j++)if(r()<noise_tau)A[i][j]=A[j][i]=1-A[i][j];return {adjacency:A,metrics:this.compute_graph_properties(A),coherence:null,status:atom_count<2?'FAILED':'PARTIAL_SOURCE',feedback_modifier:feedback_alpha*.15,reason:'Full coherence expression is clipped in source; no missing term inferred.'};}
}
class PhysicalCLCEEngine{
 constructor(){this.atomic_radii=radii;this.geometry_angles={tetrahedral:1.9106,'trigonal pyramidal':1.8675,bent:1.8234,linear:Math.PI};}
 generate_coordinates(atoms,geometry){atoms.forEach(radius);if(atoms.length>24)throw Error('Limit 24');const coords=atoms.map(()=>[0,0,0]),angle=this.geometry_angles[geometry]??Math.PI;for(let i=1;i<atoms.length;i++){const r=radius(atoms[0])+radius(atoms[i]),theta=(i-1)*angle;coords[i]=[r*Math.sin(theta),r*Math.cos(theta),0];}return coords;}
 analyze_topology(atoms,geometry,user_perturbation_distance=0){if(!Number.isFinite(user_perturbation_distance))throw Error('Invalid displacement');if(atoms.length<2)return {coherence:0,status:'REJECT',reason:'Insufficient atoms'};const coords=this.generate_coordinates(atoms,geometry);coords.at(-1)[0]+=user_perturbation_distance;const D=distances(coords);let valid=0,total=0;for(let i=0;i<atoms.length;i++)for(let j=i+1;j<atoms.length;j++){total++;const ideal=radius(atoms[i])+radius(atoms[j]);if(Math.abs(D[i][j]-ideal)<=ideal*.15)valid++;}const coherence=valid/total,audit_disposition=disposition(coherence);return {coherence,coordinates:coords,distance_matrix:D,audit_disposition,locked_topology:audit_disposition!=='REJECT',note:'All-pairs radius-distance ratio, including nonbonded pairs; not validated molecular stability.'};}
}
class StructuralTopologyEngine{
 constructor(){this.radii=radii;this.geometry_vectors={tetrahedral:[[0,0,1],[2*Math.sqrt(2)/3,0,-1/3],[-Math.sqrt(2)/3,Math.sqrt(6)/3,-1/3],[-Math.sqrt(2)/3,-Math.sqrt(6)/3,-1/3]],linear:[[0,0,1],[0,0,1]],bent:[[Math.sin(104.5*Math.PI/360),Math.cos(104.5*Math.PI/360),0],[-Math.sin(104.5*Math.PI/360),Math.cos(104.5*Math.PI/360),0]]};}
 compute_3d_topology(center_atom,peripheral_atoms,geometry,perturbation_vector=null){const basis=this.geometry_vectors[geometry];radius(center_atom);peripheral_atoms.forEach(radius);if(!basis||!peripheral_atoms.length)return {coherence:0,status:'REJECT',reason:'Invalid topology'};if(peripheral_atoms.length>basis.length)throw Error('More peripherals than source geometry vectors: source leaves extras at origin; rejected explicitly');if(perturbation_vector&&(perturbation_vector.length!==3||!perturbation_vector.every(Number.isFinite)))throw Error('Invalid vector');const coords=[[0,0,0],...peripheral_atoms.map((s,i)=>basis[i].map(v=>v*(radius(center_atom)+radius(s))))];if(perturbation_vector)coords[1]=coords[1].map((v,i)=>v+perturbation_vector[i]);let sum=0;for(let i=0;i<peripheral_atoms.length;i++){const ideal=radius(center_atom)+radius(peripheral_atoms[i]),strain=Math.abs(norm(coords[i+1])-ideal)/ideal;sum+=Math.exp(-5*strain*strain);}const topological_coherence=sum/peripheral_atoms.length,audit_disposition=disposition(topological_coherence);return {topological_coherence,coordinates:coords,audit_disposition,locked_topology:audit_disposition!=='REJECT',source_linear_vectors_coincident:geometry==='linear',note:'Dimensionless geometric score; source energy label is not a calibrated joule quantity.'};}
}
class GlobalTopologyCLCEEngine{
 constructor(){this.radii=radii;}
 resolve_network_coordinates(elements,A,perturbations=null){check(elements,A,perturbations);const n=elements.length,coords=elements.map(()=>[0,0,0]);for(let i=1;i<n;i++){const parent=A[i].findIndex(v=>v===1);if(parent>=0){const length=radius(elements[i])+radius(elements[parent]),phi=i*137.5*Math.PI/180,theta=Math.acos(1-2*i/n),direction=[Math.sin(theta)*Math.cos(phi),Math.sin(theta)*Math.sin(phi),Math.cos(theta)];coords[i]=coords[parent].map((v,k)=>v+direction[k]*length);}else coords[i]=[i,0,0];}if(perturbations)for(let i=0;i<n;i++)coords[i]=coords[i].map((v,k)=>v+perturbations[i][k]);return {coordinates:coords,distance_matrix:distances(coords)};}
 analyze_spectral_invariance(elements,A,perturbations=null){check(elements,A,perturbations);if(elements.length<2)return {coherence:0,status:'REJECT'};const {coordinates,distance_matrix:D}=this.resolve_network_coordinates(elements,A,perturbations),n=elements.length,W=zeros(n);for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(A[i][j]){const ideal=radius(elements[i])+radius(elements[j]);W[i][j]=Math.exp(-3*Math.abs(D[i][j]-ideal)/ideal);}const L=W.map((row,i)=>row.map((v,j)=>i===j?row.reduce((a,b)=>a+b,0):-v)),eigen=eigensystem(L).values,fiedler=Math.max(0,eigen[1]),spectral_coherence=1/(1+Math.exp(-fiedler));return {spectral_coherence,fiedler_value:fiedler,eigenvalues:eigen,coordinates,weights:W,audit_disposition:disposition(fiedler,.5,.1),note:'Disconnected graphs give Fiedler≈0 but the source sigmoid score≈0.5; audit uses Fiedler, not sigmoid. Coordinate construction is order-dependent.'};}
}
class QuantumCoherenceCLCEEngine{
 constructor(){this.radii=radii;}
 relax_3d_geometry(elements,A,perturbations=null,steps=50){check(elements,A,perturbations);if(!Number.isInteger(steps)||steps<0||steps>500)throw Error('Invalid relaxation steps');const r=rng(101),coords=elements.map(()=>[normalRandom(r),normalRandom(r),normalRandom(r)]);if(perturbations)for(let i=0;i<coords.length;i++)coords[i]=coords[i].map((v,k)=>v+perturbations[i][k]);for(let t=0;t<steps;t++){const F=elements.map(()=>[0,0,0]);for(let i=0;i<elements.length;i++)for(let j=0;j<elements.length;j++)if(i!==j){const diff=sub(coords[i],coords[j]),d=norm(diff)+1e-9,direction=diff.map(v=>v/d),factor=A[i][j]?-2*(d-radius(elements[i])-radius(elements[j])):.1/(d*d);F[i]=F[i].map((v,k)=>v+factor*direction[k]);}for(let i=0;i<coords.length;i++)coords[i]=coords[i].map((v,k)=>v+.05*F[i][k]);if(!coords.flat().every(Number.isFinite))throw Error('Relaxation diverged');}return coords;}
 compute_quantum_phase_coherence(elements,A,perturbations=null){check(elements,A,perturbations);const n=elements.length;if(n<2)return {coherence:0,status:'REJECT'};const coords=this.relax_3d_geometry(elements,A,perturbations),D=distances(coords),Re=zeros(n),Im=zeros(n);for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(A[i][j]){const phi=2*Math.PI*D[i][j]/1.5;Re[i][j]=Math.cos(phi);Im[i][j]=Math.sin(phi);}
 // Source H has identical complex entries on reverse edges, and is not Hermitian.
 // Match np.linalg.eigh's default lower-triangle interpretation explicitly.
 for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){Re[i][j]=Re[j][i];Im[i][j]=-Im[j][i];}
 const block=zeros(2*n);for(let i=0;i<n;i++)for(let j=0;j<n;j++){block[i][j]=Re[i][j];block[i][j+n]=-Im[i][j];block[i+n][j]=Im[i][j];block[i+n][j+n]=Re[i][j];}const eig=eigensystem(block),v=eig.vectors.at(-1),mag=elements.map((_,i)=>Math.hypot(v[i],v[i+n])),density=mag.map(a=>mag.map(b=>a*b)),off=density.flat().reduce((a,b)=>a+b,0)-mag.reduce((a,b)=>a+b*b,0),phase_coherence=Math.min(1,Math.max(0,off/(n-1))),gap=eig.values.at(-1)-eig.values.at(-3),audit_disposition=disposition(phase_coherence,.8,.4);return {phase_coherence,density_matrix_magnitude:density,coordinates:coords,audit_disposition,locked_topology:audit_disposition!=='REJECT',largest_eigenvalue:eig.values.at(-1),dominant_gap:gap,degenerate:gap<1e-8,note:'Pure-vector off-diagonal score; basis-dependent and potentially degenerate. Source Hermiticity issue resolved via explicit lower-triangle convention. Not a measured quantum coherence.'};}
}
function adjacency(scene){const ids=new Map(scene.nodes.map((n,i)=>[n.id,i])),A=zeros(scene.nodes.length);for(const e of scene.edges)A[ids.get(e.a)][ids.get(e.b)]=A[ids.get(e.b)][ids.get(e.a)]=1;return A;}
const api={CLCEEngine,PhysicalCLCEEngine,StructuralTopologyEngine,GlobalTopologyCLCEEngine,QuantumCoherenceCLCEEngine,eigensystem,adjacency,radii};if(typeof module!=='undefined')module.exports=api;root.CLCEExperimental=api;
})(globalThis);
