/* Neutral LightBench 0.1.0. Educational bookkeeping, not a molecular solver. */
(function(root){
'use strict';
const elements={H:{z:1,v:1,cap:1,color:'#eeeeff'},C:{z:6,v:4,cap:4,color:'#68d7ef'},N:{z:7,v:5,cap:3,color:'#889cff'},O:{z:8,v:6,cap:2,color:'#ff8198'},P:{z:15,v:5,cap:3,color:'#ffc268'},S:{z:16,v:6,cap:2,color:'#ffe786'}};
const h=6.62607015e-34,c=299792458;
const canonical=x=>JSON.stringify(x);
function empty(){return {version:'LIGHTBENCH/0.1.0',nodes:[],edges:[],next:1,settings:{power:1,cooling:.1,capacity:10,lightFraction:.02,wavelength:550,ambient:293.15},physics:{t:0,temperature:293.15,input:0,heatOut:0,light:0,photons:0},events:[]};}
function log(s,type,data){s.events.push({sequence:s.events.length+1,type,data:JSON.parse(canonical(data)),simulationTime:s.physics.t});}
function add(s,symbol,x=400,y=250,charge=0){if(!elements[symbol])throw Error('Unsupported element'); const n={id:'a'+s.next++,symbol,x,y,charge};s.nodes.push(n);log(s,'add',n);return n;}
function connect(s,a,b,order=1){if(a===b||!s.nodes.some(n=>n.id===a)||!s.nodes.some(n=>n.id===b)||![1,2,3].includes(order))throw Error('Invalid bond');if(s.edges.some(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a)))throw Error('Bond already exists');const e={a,b,order};s.edges.push(e);log(s,'connect',e);return e;}
function remove(s,id){s.nodes=s.nodes.filter(n=>n.id!==id);s.edges=s.edges.filter(e=>e.a!==id&&e.b!==id);log(s,'remove',{id});}
function removeBond(s,a,b){s.edges=s.edges.filter(e=>!((e.a===a&&e.b===b)||(e.a===b&&e.b===a)));log(s,'removeBond',{a,b});}
function historical(initial,final,stress,wavelength=550){if(![initial,final,stress,wavelength].every(Number.isFinite)||initial<0||initial>1||final<0||final>1||wavelength<=0)throw Error('Invalid comparison input');const energy=Math.max(0,1e-19*(4.2*Math.abs(initial-final)+1.8*stress));return {energy,photons:energy/(6.626e-34*3e8/(wavelength*1e-9))};}
function inspect(s){let components=0;const seen=new Set(),adj=new Map(s.nodes.map(n=>[n.id,[]]));for(const e of s.edges){adj.get(e.a).push(e.b);adj.get(e.b).push(e.a);}function visit(id){seen.add(id);for(const b of adj.get(id))if(!seen.has(b))visit(b);}for(const n of s.nodes)if(!seen.has(n.id)){components++;visit(n.id);}const warnings=[];const atoms=s.nodes.map(n=>{const p=elements[n.symbol],used=s.edges.filter(e=>e.a===n.id||e.b===n.id).reduce((v,e)=>v+e.order,0);if(used>p.cap)warnings.push(n.id+' exceeds this simplified neutral bond template');if(p.z-n.charge<0)warnings.push(n.id+' has a negative electron count');return {...n,electrons:p.z-n.charge,valenceElectrons:p.v-n.charge,bondOrderSum:used,unassignedValence:p.v-n.charge-used};});return {atoms,components,cycles:s.edges.length-s.nodes.length+components,branches:s.nodes.filter(n=>adj.get(n.id).length>=3).length,electrons:atoms.reduce((v,n)=>v+n.electrons,0),charge:s.nodes.reduce((v,n)=>v+n.charge,0),warnings};}
function candidates(s){const out=[];for(const H of s.nodes.filter(n=>n.symbol==='H')){const bonds=s.edges.filter(e=>e.a===H.id||e.b===H.id);if(bonds.length!==1)continue;const donor=s.nodes.find(n=>n.id===(bonds[0].a===H.id?bonds[0].b:bonds[0].a));if(!['N','O','S'].includes(donor.symbol))continue;for(const a of s.nodes.filter(n=>['N','O','S'].includes(n.symbol)&&n.id!==donor.id)){if(s.edges.some(e=>(e.a===H.id&&e.b===a.id)||(e.b===H.id&&e.a===a.id)))continue;const d=Math.hypot(a.x-H.x,a.y-H.y),ux=H.x-donor.x,uy=H.y-donor.y,vx=a.x-H.x,vy=a.y-H.y;const cosine=(ux*vx+uy*vy)/(Math.hypot(ux,uy)*d||1);if(d<150&&d>10&&cosine>.5)out.push({donor:donor.id,hydrogen:H.id,acceptor:a.id,distancePixels:d});}}return out;}
function step(s,dt=.05){if(!Number.isFinite(dt)||dt<=0||dt>1)throw Error('dt out of range');const p=s.physics,k=s.settings,input=k.power*dt,light=input*k.lightFraction,stored=k.capacity*(p.temperature-k.ambient),heat=Math.min(Math.max(0,stored+input-light),k.cooling*Math.max(0,p.temperature-k.ambient)*dt);p.temperature+=(input-light-heat)/k.capacity;p.input+=input;p.light+=light;p.heatOut+=heat;p.photons+=light/(h*c/(k.wavelength*1e-9));p.t+=dt;return p;}
function residual(s){return s.physics.input-s.physics.light-s.physics.heatOut-s.settings.capacity*(s.physics.temperature-s.settings.ambient);}
function validate(s){if(!s||s.version!=='LIGHTBENCH/0.1.0'||!Array.isArray(s.nodes)||!Array.isArray(s.edges)||!Array.isArray(s.events))throw Error('Unsupported scene');if(s.nodes.length>1000||s.edges.length>4000||s.events.length>20000)throw Error('Scene exceeds safety limits');const ids=new Set();for(const n of s.nodes){if(!n||!/^a[1-9][0-9]*$/.test(n.id)||ids.has(n.id)||!elements[n.symbol]||![n.x,n.y,n.charge].every(Number.isFinite)||!Number.isInteger(n.charge)||Math.abs(n.charge)>16)throw Error('Invalid atom');ids.add(n.id);}const pairs=new Set();for(const e of s.edges){const key=[e.a,e.b].sort().join(':');if(!ids.has(e.a)||!ids.has(e.b)||e.a===e.b||![1,2,3].includes(e.order)||pairs.has(key))throw Error('Invalid edge');pairs.add(key);}if(!Number.isInteger(s.next)||s.next<1||s.nodes.some(n=>Number(n.id.slice(1))>=s.next))throw Error('Invalid ID counter');const k=s.settings;if(!k||!Object.values(k).every(Number.isFinite)||k.power<0||k.power>100||k.cooling<0||k.cooling>100||k.capacity<=0||k.capacity>10000||k.lightFraction<0||k.lightFraction>1||k.wavelength<200||k.wavelength>1000||k.ambient<0)throw Error('Invalid budget');if(!s.physics||!Object.values(s.physics).every(Number.isFinite)||s.physics.temperature<k.ambient||['t','input','heatOut','light','photons'].some(k=>s.physics[k]<0))throw Error('Invalid physics');if(Math.abs(residual(s))>1e-7*Math.max(1,s.physics.input))throw Error('Energy ledger mismatch');return s;}
function graphMetrics(s){const n=s.nodes.length,index=new Map(s.nodes.map((a,i)=>[a.id,i])),A=Array.from({length:n},()=>Array(n).fill(0));for(const e of s.edges){A[index.get(e.a)][index.get(e.b)]=1;A[index.get(e.b)][index.get(e.a)]=1;}let triangles=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(A[i][j])for(let k=j+1;k<n;k++)if(A[i][k]&&A[j][k])triangles++;return {density:n<2?0:2*s.edges.length/(n*(n-1)),triangles,branchNodes:A.filter(row=>row.reduce((a,b)=>a+b,0)>=3).length};}
function hermes(attacks,declared){if(!Number.isInteger(declared)||declared<=0||!Array.isArray(attacks))throw Error('Declare at least one family');const families=new Set();const rows=attacks.map(a=>{if(typeof a.family!=='string'||!a.family.trim()||![a.delta,a.magnitude,a.sensitivity].every(Number.isFinite)||a.delta<0||a.magnitude<=0||a.sensitivity<=0)throw Error('Attack requires nonnegative change and positive magnitude/sensitivity');families.add(a.family.trim());return {...a,normalized:a.delta/a.magnitude,sensitive:a.delta/(a.magnitude*a.sensitivity)};});if(families.size>declared)throw Error('Tested families exceed declared benchmark');const damage=rows.length?Math.max(...rows.map(a=>a.sensitive)):null;return {rows,damage,resistance:damage===null?null:1/(1+damage),coverage:families.size/declared,counterexample:rows.some(a=>a.counterexample===true),status:rows.some(a=>a.counterexample===true)?'COUNTEREXAMPLE_REPORTED':rows.length?'DECLARED_TESTS_ONLY':'UNTESTED'};}
function weightedLoss(prediction,relationships,conservation,provenance,lambda,mu,omega){const a=[prediction,relationships,conservation,provenance,lambda,mu,omega];if(!a.every(Number.isFinite)||a.some(n=>n<0))throw Error('Use nonnegative finite terms and weights');return prediction+lambda*relationships+mu*conservation+omega*provenance;}
function configureThermal(s,ambient,capacity){if(!Number.isFinite(ambient)||ambient<0||ambient>10000||!Number.isFinite(capacity)||capacity<=0||capacity>10000)throw Error('Invalid thermal setup');s.settings.ambient=ambient;s.settings.capacity=capacity;s.physics={...empty().physics,temperature:ambient};log(s,'thermalReset',{ambient,capacity});}
function fusionBudget(count,neutrinoFraction=.022,lightFraction=.2){if(!Number.isInteger(count)||count<0||count>1e6||![neutrinoFraction,lightFraction].every(Number.isFinite)||neutrinoFraction<0||neutrinoFraction>1||lightFraction<0||lightFraction>1)throw Error('Invalid fusion budget');const total=count*26.7e6*1.602176634e-19,neutrinos=total*neutrinoFraction,available=total-neutrinos,light=available*lightFraction,heat=available-light;return {hydrogenConsumed:4*count,heliumProduced:count,total,neutrinos,light,heat,massDefect:total/(c*c),residual:total-neutrinos-light-heat};}
class History{constructor(limit=100){this.limit=limit;this.past=[];this.future=[];}checkpoint(s){this.past.push(JSON.parse(JSON.stringify(s)));if(this.past.length>this.limit)this.past.shift();this.future=[];}restore(s,from,to,type){if(!from.length)return s;to.push(JSON.parse(JSON.stringify(s)));const saved=from.pop(),events=s.events; saved.next=Math.max(saved.next,s.next);saved.events=events;log(saved,type,{restoredSnapshotTime:saved.physics.t});return saved;}undo(s){return this.restore(s,this.past,this.future,'undo');}redo(s){return this.restore(s,this.future,this.past,'redo');}}
function disulfide(){const s=empty();for(let row=0;row<2;row++){for(let i=0;i<6;i++)add(s,'C',130+i*100,150+row*220);for(let i=1;i<6;i++)connect(s,'a'+(row*6+i),'a'+(row*6+i+1));}for(const col of [1,4]){const a=add(s,'S',130+col*100,215),b=add(s,'S',130+col*100,305);connect(s,'a'+(col+1),a.id);connect(s,a.id,b.id);connect(s,b.id,'a'+(col+7));}return s;}
function preset(name){if(name==='disulfide')return disulfide();const s=empty();if(name==='methane'||name==='singleWater'){add(s,name==='methane'?'C':'O',400,250);const count=name==='methane'?4:2;for(let i=0;i<count;i++){const a=add(s,'H',400+100*Math.cos(i*2*Math.PI/count),250+100*Math.sin(i*2*Math.PI/count));connect(s,'a1',a.id);}return s;}if(name==='water'){add(s,'O',240,250);add(s,'H',300,210);add(s,'H',200,200);add(s,'O',390,150);add(s,'H',445,165);add(s,'H',385,90);connect(s,'a1','a2');connect(s,'a1','a3');connect(s,'a4','a5');connect(s,'a4','a6');}else {for(let i=0;i<6;i++)add(s,'C',400+100*Math.cos(i*Math.PI/3),250+100*Math.sin(i*Math.PI/3));for(let i=0;i<6;i++)connect(s,'a'+(i+1),'a'+((i+1)%6+1));if(name==='bridge'){add(s,'S',220,250);add(s,'S',150,250);connect(s,'a4','a7');connect(s,'a7','a8');}}return s;}
const api={graphMetrics,hermes,weightedLoss,configureThermal,History,fusionBudget,disulfide,elements,h,c,empty,add,connect,remove,removeBond,historical,inspect,candidates,step,residual,validate,preset};if(typeof module!=='undefined')module.exports=api;root.LightBench=api;
})(typeof globalThis==='undefined'?this:globalThis);
