const assert=require('node:assert/strict'),X=require('./engines'),M=require('./model');let count=0;function test(n,f){f();count++;console.log('PASS '+n);}const close=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`);
const atoms=['C','H','H','H','H'],A=[[0,1,1,1,1],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]];
test('graph triangle count',()=>{const r=new X.CLCEEngine().compute_graph_properties([[0,1,1],[1,0,1],[1,1,0]]);assert.equal(r.triangles,1);assert.equal(r.density,1);});
test('synthetic graph deterministic and symmetric',()=>{const e=new X.CLCEEngine(),a=e.run_flow(8,.5,.2,1),b=e.run_flow(8,.5,.2,1);assert.deepEqual(a,b);a.adjacency.forEach((row,i)=>row.forEach((v,j)=>assert.equal(v,a.adjacency[j][i])));assert.equal(a.coherence,null);});
test('invalid graph controls rejected',()=>assert.throws(()=>new X.CLCEEngine().run_flow(5,2,0,0)));
test('geometry pair radius length',()=>{const r=new X.PhysicalCLCEEngine().analyze_topology(['O','H'],'bent');close(r.distance_matrix[0][1],1.10);assert.equal(r.coherence,1);});
test('geometry displacement changes score',()=>{const e=new X.PhysicalCLCEEngine();assert.ok(e.analyze_topology(['O','H'],'bent',10).coherence<e.analyze_topology(['O','H'],'bent',0).coherence);});
test('tetrahedral vectors give expected angle',()=>{const e=new X.StructuralTopologyEngine(),r=e.compute_3d_topology('C',['H','H','H','H'],'tetrahedral');close(r.topological_coherence,1);const a=r.coordinates[1],b=r.coordinates[2];close(a.reduce((v,x,i)=>v+x*b[i],0)/(1.14*1.14),-1/3);});
test('strain perturbation changes score',()=>{const e=new X.StructuralTopologyEngine();assert.ok(e.compute_3d_topology('C',['H'],'tetrahedral',[1,0,0]).topological_coherence<1);});
test('source linear overlap is retained explicitly',()=>{const r=new X.StructuralTopologyEngine().compute_3d_topology('C',['H','H'],'linear');assert.deepEqual(r.coordinates[1],r.coordinates[2]);assert.equal(r.source_linear_vectors_coincident,true);});
test('excess peripherals rejected rather than left at origin',()=>assert.throws(()=>new X.StructuralTopologyEngine().compute_3d_topology('C',['H','H','H'],'linear')));
test('symmetric eigensolver analytic result',()=>{const r=X.eigensystem([[2,-1],[-1,2]]);close(r.values[0],1);close(r.values[1],3);});
test('spectral ideal pair Fiedler two',()=>{const r=new X.GlobalTopologyCLCEEngine().analyze_spectral_invariance(['H','H'],[[0,1],[1,0]]);close(r.fiedler_value,2);});
test('disconnected spectrum is not proof of coherence',()=>{const r=new X.GlobalTopologyCLCEEngine().analyze_spectral_invariance(['H','H'],[[0,0],[0,0]]);close(r.fiedler_value,0);close(r.spectral_coherence,.5);assert.equal(r.audit_disposition,'REJECT');});
test('connected graph eigenvalues nonnegative',()=>{const r=new X.GlobalTopologyCLCEEngine().analyze_spectral_invariance(atoms,A);assert.ok(r.eigenvalues.every(v=>v>-1e-9));});
test('relaxation reproducible',()=>{const e=new X.QuantumCoherenceCLCEEngine();assert.deepEqual(e.relax_3d_geometry(atoms,A),e.relax_3d_geometry(atoms,A));});
test('phase density trace one and bounded score',()=>{const r=new X.QuantumCoherenceCLCEEngine().compute_quantum_phase_coherence(atoms,A);close(r.density_matrix_magnitude.reduce((s,row,i)=>s+row[i],0),1);assert.ok(r.phase_coherence>=0&&r.phase_coherence<=1);});
test('phase dominant degeneracy reported',()=>{const r=new X.QuantumCoherenceCLCEEngine().compute_quantum_phase_coherence(['H','H'],[[0,0],[0,0]]);assert.equal(r.degenerate,true);});
test('asymmetric input rejected',()=>assert.throws(()=>new X.GlobalTopologyCLCEEngine().analyze_spectral_invariance(['H','H'],[[0,1],[0,0]])));
test('all experiments leave thermal scene intact',()=>{const s=M.preset('water'),before=JSON.stringify(s),a=s.nodes.map(n=>n.symbol),A=X.adjacency(s);new X.GlobalTopologyCLCEEngine().analyze_spectral_invariance(a,A);new X.QuantumCoherenceCLCEEngine().compute_quantum_phase_coherence(a,A);assert.equal(JSON.stringify(s),before);});
test('24 atom guard',()=>assert.throws(()=>new X.QuantumCoherenceCLCEEngine().relax_3d_geometry(Array(25).fill('H'),Array.from({length:25},()=>Array(25).fill(0)))));
console.log(`${count} engine checks passed`);
