const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve(__dirname,'LightBench.html'));let checks=0;function check(){checks++;}
assert.equal(await page.locator('circle.atom').count(),6);check();
await page.getByRole('button',{name:'Run',exact:true}).click();await page.waitForTimeout(250);await page.getByRole('button',{name:'Pause',exact:true}).click();assert.ok(await page.evaluate(()=>state.physics.input>0&&Math.abs(LightBench.residual(state))<1e-9));check();
await page.getByRole('button',{name:'Reset energy'}).click();assert.equal(await page.evaluate(()=>state.physics.input),0);check();
await page.selectOption('#preset','ring');await page.click('#loadPreset');assert.equal(await page.evaluate(()=>LightBench.inspect(state).cycles),1);check();
await page.click('[data-id="a1"]');await page.locator('input[aria-label="Formal charge"]').fill('1');await page.locator('input[aria-label="Formal charge"]').dispatchEvent('change');assert.equal(await page.evaluate(()=>state.nodes[0].charge),1);check();
const rect=await page.locator('svg').boundingBox();await page.mouse.move(rect.x+rect.width*500/800,rect.y+rect.height*250/520);await page.mouse.down();await page.mouse.move(rect.x+rect.width*540/800,rect.y+rect.height*230/520);await page.mouse.up();assert.ok(await page.evaluate(()=>state.nodes[0].x>520));check();
await page.getByRole('button',{name:'Clear',exact:true}).click();await page.getByRole('button',{name:'C',exact:true}).click();await page.mouse.click(rect.x+rect.width*.4,rect.y+rect.height*.5);await page.mouse.click(rect.x+rect.width*.6,rect.y+rect.height*.5);await page.selectOption('#mode','bond');await page.click('[data-id="a1"]');await page.click('[data-id="a2"]');assert.equal(await page.evaluate(()=>state.edges.length),1);check();
const downloadPromise=page.waitForEvent('download');await page.click('#save');const download=await downloadPromise;const saved=path.join(__dirname,'browser-scene.json');await download.saveAs(saved);const original=JSON.parse(fs.readFileSync(saved,'utf8'));assert.ok(original.sha256);check();
await page.click('#clear');await page.locator('#file').setInputFiles(saved);await page.waitForFunction(()=>state.nodes.length===2);assert.equal(await page.evaluate(()=>state.edges.length),1);check();
original.payload=original.payload.replace('"symbol":"C"','"symbol":"O"');fs.writeFileSync(saved,JSON.stringify(original));await page.locator('#file').setInputFiles(saved);await page.waitForFunction(()=>document.getElementById('message').textContent.includes('hash mismatch'));assert.equal(await page.evaluate(()=>state.nodes[0].symbol),'C');check();
await page.screenshot({path:path.join(__dirname,'preview.png'),fullPage:true});assert.deepEqual(errors,[]);check();
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check();fs.unlinkSync(saved);console.log(JSON.stringify({checks,browser:await browser.version(),pageErrors:errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
