const assert=require('node:assert/strict'),M=require('./model.js');let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
test('neutral water electron count',()=>assert.equal(M.inspect(M.preset('water')).electrons,20));
test('formal charge changes electrons',()=>{const s=M.empty();M.add(s,'O',1,1,-1);assert.equal(M.inspect(s).electrons,9);});
test('independent cycle count',()=>assert.equal(M.inspect(M.preset('ring')).cycles,1));
test('branch count',()=>{const s=M.empty();for(let i=0;i<4;i++)M.add(s,'C');for(let i=2;i<5;i++)M.connect(s,'a1','a'+i);assert.equal(M.inspect(s).branches,1);});
test('hydrogen motif responds to geometry',()=>{const s=M.preset('water');assert.equal(M.candidates(s).length,1);s.nodes[3].x=700;assert.equal(M.candidates(s).length,0);});
test('covalent bond is not H candidate',()=>{const s=M.preset('water');M.connect(s,'a2','a4');assert.equal(M.candidates(s).length,0);});
test('duplicate bond rejected',()=>assert.throws(()=>M.connect(M.preset('ring'),'a2','a1')));
test('removed atom removes bonds',()=>{const s=M.preset('ring');M.remove(s,'a1');assert.equal(s.edges.length,4);assert.equal(M.inspect(s).cycles,0);});
test('budget conserves energy over 10000 steps',()=>{const s=M.empty();for(let i=0;i<10000;i++)M.step(s);assert.ok(Math.abs(M.residual(s))<1e-8);M.validate(s);});
test('all-light budget produces no heat',()=>{const s=M.empty();s.settings.lightFraction=1;M.step(s,1);assert.equal(s.physics.temperature,293.15);assert.equal(s.physics.light,1);});
test('zero power yields no invented photons',()=>{const s=M.empty();s.settings.power=0;for(let i=0;i<100;i++)M.step(s);assert.equal(s.physics.photons,0);});
test('550nm photon conversion',()=>{const s=M.empty();M.step(s,1);assert.ok(Math.abs(s.physics.photons*(M.h*M.c/550e-9)-s.physics.light)<1e-15);});
test('fresh process snapshot recovery',()=>{const s=M.preset('bridge');M.step(s);const child=require('node:child_process').spawnSync(process.execPath,['-e',"const M=require('./model');const s=M.validate(JSON.parse(process.argv[1]));console.log(JSON.stringify(M.inspect(s)))",JSON.stringify(s)],{cwd:__dirname,encoding:'utf8'});assert.equal(child.status,0);assert.deepEqual(JSON.parse(child.stdout),M.inspect(s));});
test('malicious settings rejected',()=>{const s=M.empty();s.settings.lightFraction=2;assert.throws(()=>M.validate(s));});
test('tampered energy rejected',()=>{const s=M.empty();s.physics.input=1;assert.throws(()=>M.validate(s));});
test('bad graph rejected',()=>{const s=M.preset('ring');s.edges[0].b='missing';assert.throws(()=>M.validate(s));});
test('edit journal monotonic',()=>{const s=M.preset('bridge');assert.deepEqual(s.events.map(e=>e.sequence),s.events.map((e,i)=>i+1));});
test('remove bond preserves atoms',()=>{const s=M.preset('ring');M.removeBond(s,'a1','a2');assert.equal(s.nodes.length,6);assert.equal(s.edges.length,5);assert.equal(M.inspect(s).cycles,0);});
test('historical rupture rule',()=>{const r=M.historical(.92,.55,.85);assert.ok(Math.abs(r.energy-3.084e-19)<1e-32);assert.ok(r.photons>0);});
test('historical negative energy clamp',()=>assert.equal(M.historical(.5,.5,-1).energy,0));
test('undo redo restores graph and keeps journal',()=>{let s=M.empty();const h=new M.History();h.checkpoint(s);M.add(s,'C');s=h.undo(s);assert.equal(s.nodes.length,0);assert.equal(s.events.at(-1).type,'undo');s=h.redo(s);assert.equal(s.nodes.length,1);assert.equal(s.events.at(-1).type,'redo');});
test('undo never reuses an atom ID',()=>{let s=M.empty();const h=new M.History();h.checkpoint(s);M.add(s,'H');s=h.undo(s);assert.equal(M.add(s,'O').id,'a2');});
test('edit after undo invalidates redo',()=>{let s=M.empty();const h=new M.History();h.checkpoint(s);M.add(s,'C');s=h.undo(s);h.checkpoint(s);M.add(s,'N');assert.equal(h.future.length,0);});
test('history restores conserved thermal snapshot',()=>{let s=M.empty();const h=new M.History();h.checkpoint(s);M.step(s);s=h.undo(s);assert.equal(s.physics.input,0);assert.equal(M.residual(s),0);s=h.redo(s);M.validate(s);});
test('double disulfide connects both chains',()=>{const s=M.disulfide();assert.equal(s.nodes.filter(n=>n.symbol==='S').length,4);assert.equal(M.inspect(s).components,1);assert.equal(M.inspect(s).cycles,1);assert.equal(M.inspect(s).warnings.length,0);});
test('fusion conservation and nuclear counts',()=>{const f=M.fusionBudget(10);assert.equal(f.hydrogenConsumed,40);assert.equal(f.heliumProduced,10);assert.ok(Math.abs(f.residual)<1e-24);assert.ok(Math.abs(f.massDefect*M.c*M.c-f.total)<1e-24);});
test('fusion zero and invalid input',()=>{assert.equal(M.fusionBudget(0).total,0);assert.throws(()=>M.fusionBudget(1.5));assert.throws(()=>M.fusionBudget(1,.1,2));});
test('Hermes worst attack and coverage',()=>{const r=M.hermes([{family:'a',delta:2,magnitude:2,sensitivity:.5},{family:'a',delta:0,magnitude:1,sensitivity:1}],2);assert.equal(r.damage,2);assert.equal(r.resistance,1/3);assert.equal(r.coverage,.5);});
test('Hermes no attacks remains untested',()=>{const r=M.hermes([],2);assert.equal(r.resistance,null);assert.equal(r.status,'UNTESTED');});
test('Hermes counterexample independent of score',()=>{assert.equal(M.hermes([{family:'a',delta:0,magnitude:1,sensitivity:1,counterexample:true}],1).status,'COUNTEREXAMPLE_REPORTED');});
test('Hermes rejects zero normalization',()=>assert.throws(()=>M.hermes([{family:'a',delta:1,magnitude:0,sensitivity:1}],1)));
test('weighted objective distinct from resistance',()=>assert.equal(M.weightedLoss(1,2,3,4,2,3,4),30));
test('thermal reset sets Kelvin and preserves balance',()=>{const s=M.empty();M.step(s);M.configureThermal(s,310.15,20);assert.equal(s.physics.temperature,310.15);assert.equal(s.physics.input,0);M.step(s,1);assert.ok(Math.abs(s.physics.temperature-310.199)<1e-10);M.validate(s);});
test('graph triangle is not a six-member ring',()=>{assert.equal(M.graphMetrics(M.preset('ring')).triangles,0);const s=M.empty();for(let i=0;i<3;i++)M.add(s,'C');M.connect(s,'a1','a2');M.connect(s,'a2','a3');M.connect(s,'a3','a1');assert.equal(M.graphMetrics(s).triangles,1);assert.equal(M.graphMetrics(s).density,1);});
test('graph metrics invariant to array ordering',()=>{const s=M.disulfide(),before=M.graphMetrics(s);s.nodes.reverse();s.edges.reverse();assert.deepEqual(M.graphMetrics(s),before);});
test('methane star preset electron count and branches',()=>{const s=M.preset('methane');assert.equal(s.nodes.length,5);assert.equal(M.inspect(s).electrons,10);assert.equal(M.inspect(s).branches,1);M.validate(s);});
test('single water preset electron count',()=>{const s=M.preset('singleWater');assert.equal(s.nodes.length,3);assert.equal(M.inspect(s).electrons,10);M.validate(s);});
console.log(`${count} model checks passed`);
