'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),M=require('../model'),fs=require('node:fs'),vm=require('node:vm');
test('SHA256 portable implementation matches independent Node crypto',()=>{for(const x of ['', 'abc','Neutral ♥ π', 'x'.repeat(10000)])assert.equal(M.sha256(x),crypto.createHash('sha256').update(x).digest('hex'));});
test('canonical JSON is independent of key insertion order',()=>assert.equal(M.canonical({b:2,a:1}),M.canonical({a:1,b:2})));
test('initial cold null has no transfers without heating',()=>{const s=M.simulate({...M.defaults,heater:0},'sham',60).state;assert.equal(s.boiler,1);assert.equal(s.returned,0);assert.equal(M.energy(s),0);});
test('default loop circulates with explicit positive heat input/output',()=>{const s=M.simulate(M.defaults).state;assert.ok(s.returned>1);assert.ok(s.Qin>0&&s.Qout>0);});
test('mass and energy conserved across parameter extremes and interventions',()=>{for(const heater of [0,.1,.3])for(const cooling of [0,.5,1])for(const pump of [0,.5,1])for(const valve of [0,.5,1])for(const connected of [true,false]){const p={...M.defaults,heater,cooling,pump,valve,steamConnected:connected,returnConnected:connected};let s=M.initial();for(let i=0;i<1200;i++){s=M.step(s,p);for(const k of ['boiler','vapour','chamber','condensate','returnTank','U'])assert.ok(s[k]>=-1e-12,k);const b=M.balances(s);assert.ok(Math.abs(b.massResidual)<1e-10);assert.ok(Math.abs(b.energyResidual)<1e-9);}}});
test('cut return edge reduces returned inventory, not total mass',()=>{const c=M.compare(M.defaults,'return-cut');assert.ok(c.delta>0);assert.ok(Math.abs(M.mass(c.perturbed.state)-1)<1e-10);});
test('sham pair matches all states exactly',()=>{const c=M.compare(M.defaults,'sham');assert.deepEqual(c.baseline,c.perturbed);assert.equal(c.delta,0);assert.equal(c.relativeChange,0);});
test('zero baseline reports relative change as undefined',()=>assert.equal(M.compare({...M.defaults,heater:0},'return-cut').relativeChange,null));
test('paired runs identical before frozen intervention boundary',()=>{const c=M.compare(M.defaults,'steam-cut');assert.deepEqual(c.baseline.trace.filter(x=>x.t<20),c.perturbed.trace.filter(x=>x.t<20));assert.equal(c.protocol.cutAt,20);});
test('comparison does not mutate input parameters',()=>{const p={...M.defaults,returnConnected:false};const before=M.canonical(p);M.compare(p,'return-cut');assert.equal(M.canonical(p),before);});
test('invalid controls and timestep rejected',()=>{for(const p of [{heater:-1},{pump:2},{valve:NaN},{cooling:Infinity},{returnConnected:0}])assert.throws(()=>M.step(M.initial(),p));for(const dt of [0,-1,.5,NaN])assert.throws(()=>M.step(M.initial(),M.defaults,dt));assert.throws(()=>M.compare(M.defaults,'unknown'));});
function receipt(records,kind,s,p,steps=0,extra={}){records.push(M.append(records,{version:M.VERSION,kind,state:M.clone(s),config:M.clone(p),steps,...extra}));}
test('append-only receipt hashes/order and altered content detection',()=>{const r=[],p=M.config(M.defaults),s=M.initial();receipt(r,'reset',s,p);receipt(r,'pause',s,p);assert.equal(M.verify(r).count,2);const bad=M.clone(r);bad[0].payload.state.boiler=2;assert.throws(()=>M.verify(bad));const reorder=M.clone(r).reverse();assert.throws(()=>M.verify(reorder));});
test('replay recovers controls, transfers and multiple runs exactly',()=>{const r=[];let p=M.config(M.defaults),s=M.initial();receipt(r,'reset',s,p);for(let i=0;i<253;i++)s=M.step(s,p);receipt(r,'checkpoint',s,p,253);p={...p,returnConnected:false};receipt(r,'config',s,p);for(let i=0;i<117;i++)s=M.step(s,p);receipt(r,'step',s,p,117);assert.deepEqual(M.replay(r),{state:s,config:p});s=M.initial();receipt(r,'reset',s,p);assert.deepEqual(M.replay(r).state,s);});
test('rehashed impossible state fails deterministic replay',()=>{const r=[],p=M.config(M.defaults),s=M.initial();receipt(r,'reset',s,p);s.boiler=.5;receipt(r,'checkpoint',s,p);M.verify(r);assert.throws(()=>M.replay(r));});
function ui(storageData=null){
 class E{constructor(id){this.id=id;this.value='1';this.checked=true;this.style={};this.attrs={};this.events={};this.children=[];this.textContent='';this.classList={toggle:()=>{}};}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,fn){this.events[k]=fn;}append(...v){this.children.push(...v);}replaceChildren(){this.children=[];}click(){}}
 const ids=[...fs.readFileSync(require('node:path').join(__dirname,'../index.template.html'),'utf8').matchAll(/id="([^"]+)"/g)].map(x=>x[1]);const el=Object.fromEntries(ids.map(id=>[id,new E(id)]));el.intervention.value='return-cut';const data=new Map();if(storageData)data.set('neutral-atlas-example-c-v1',storageData);let frame;const ctx={AtlasC:M,MODEL_SOURCE:fs.readFileSync(require('node:path').join(__dirname,'../model.js'),'utf8'),document:{getElementById:id=>{assert.ok(el[id],id);return el[id];},createElement:()=>new E(),hidden:false},localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},requestAnimationFrame:f=>{frame=f;},window:{addEventListener:()=>{}},Date,JSON,Number,Math,setTimeout:()=>{},URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},Blob};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8'),ctx);
 return {el,data,call:(id,type='click')=>el[id].events[type](),frame:time=>frame(time),records:()=>JSON.parse(data.get('neutral-atlas-example-c-v1'))};
}
test('UI boots empty without overwriting history; step and config are replayable',()=>{const u=ui();assert.equal(u.records().length,0);u.call('step');u.el.cooling.value='.2';u.call('cooling','change');assert.equal(M.replay(u.records()).config.cooling,.2);assert.equal(u.el.time.textContent,'1.0 s');u.call('verify');assert.match(u.el.storage.textContent,/PASS/);});
test('UI paired comparison chart and receipt are created',()=>{const u=ui();u.call('compare');assert.ok(u.el.baselinePlot.attrs.d.startsWith('M'));assert.match(u.el.result.textContent,/Difference detected/);assert.equal(u.records().at(-1).payload.comparison.evidence,'SIMULATION');});
test('UI new run retains prefix and restored session matches',()=>{const u=ui();u.call('step');const old=M.canonical(u.records());u.call('reset');const r=u.records();assert.equal(M.canonical(r.slice(0,2)),old);const v=ui(JSON.stringify(r));assert.equal(v.el.time.textContent,'0.0 s');assert.equal(v.records().length,r.length);});
test('UI corrupt saved history is locked and not overwritten',()=>{const u=ui();u.call('step');const r=u.records();r[0].hash='bad';const raw=JSON.stringify(r),v=ui(raw);v.call('step');assert.equal(v.data.get('neutral-atlas-example-c-v1'),raw);assert.match(v.el.storage.textContent,/locked/);});
test('UI rejects concurrent tab overwrite',()=>{const u=ui();u.call('step');u.data.set('neutral-atlas-example-c-v1','[]');u.call('step');assert.equal(u.data.get('neutral-atlas-example-c-v1'),'[]');assert.match(u.el.storage.textContent,/Another tab/);});
test('UI replay pauses and returns to live without changing model',()=>{const u=ui();u.call('step');const h=M.verify(u.records()).head;u.el.replay.value='1';u.call('replay','input');assert.match(u.el.viewNote.textContent,/REPLAY/);assert.equal(u.el.time.textContent,'0.0 s');u.call('live');assert.equal(u.el.time.textContent,'1.0 s');assert.equal(M.verify(u.records()).head,h);});

test('continuous replay reconstructs intermediate ticks without changing receipts',()=>{const r=[],p=M.config(M.defaults);let s=M.initial();receipt(r,'reset',s,p);for(let i=0;i<10;i++)s=M.step(s,p);receipt(r,'step',s,p,10);const head=M.verify(r).head;const q=M.recoverAt(r,1,5);assert.equal(q.state.t,.5);assert.equal(M.verify(r).head,head);assert.throws(()=>M.recoverAt(r,1,11));});
test('UI within-checkpoint replay reconstructs rather than interpolates',()=>{const u=ui();u.call('step');u.el.replay.value='1';u.call('replay','input');assert.equal(u.el.ticks.max,10);u.el.ticks.value='5';u.call('ticks','input');assert.equal(u.el.time.textContent,'0.5 s');});
