const assert=require('node:assert/strict');global.crypto=require('node:crypto').webcrypto;const M=require('./model.js');
const image={id:'image-1',name:'test.png',sha256:'a'.repeat(64),width:800,height:600,view:'front',data:null};
const mark=(id,points)=>({id,image_id:image.id,kind:'landmark',label:id,points,ends:null,part_id:null,confidence:null,author:'human',method:'manual',status:'accepted'});
(async()=>{let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}const s={version:1,images:[image],annotations:[mark('a',[[20,30]]),mark('b',[[60,80]])]};
test('valid geometry',()=>M.valid(s));for(const [name,change]of [['out of bounds',d=>d.annotations[0].points=[[801,0]]],['duplicate ID',d=>d.annotations[1].id='a'],['missing source',d=>d.annotations[0].image_id='none'],['invalid confidence',d=>d.annotations[0].confidence=2],['unsafe image MIME',d=>d.images[0].data='data:image/svg+xml;base64,AAAA'],['invalid AI provenance',d=>{d.annotations[0].author='ai';d.annotations[0].method='manual'}]])test(name,()=>{const d=M.clone(s);change(d);assert.throws(()=>M.valid(d))});
test('region minimum vertices',()=>{const d=M.clone(s);d.annotations[0].kind='region';assert.throws(()=>M.valid(d))});test('connection references',()=>{const d=M.clone(s);d.annotations.push({...mark('c',[]),kind:'connection',ends:['a','missing']});assert.throws(()=>M.valid(d))});
const l=new M.Ledger();await l.append('source',s);let d=M.clone(s);d.annotations[0].label='revised';await l.append('correct label',d);await l.undo();test('append-only restoration',()=>{assert.equal(l.project.events.length,3);assert.equal(l.project.state.annotations[0].label,'a')});const fresh=new M.Ledger();await fresh.load(JSON.parse(JSON.stringify(l.project)));test('fresh file recovery',()=>assert.deepEqual(fresh.project,l.project));
for(const [name,change]of [['tampered historical state',p=>p.events[0].state.annotations[0].label='tampered'],['reordered history',p=>p.events.reverse()],['mismatched current state',p=>p.state.annotations=[]]]){const p=M.clone(l.project);change(p);await assert.rejects(()=>M.verify(p));count++;console.log('PASS '+name)}
console.log(`${count} tests passed`);
})().catch(e=>{console.error(e);process.exit(1)});
